store 1 to super
do while super # 20
replace first with "this must go into the field"
append blank
store super + 1 to super
store "this is a test" to first
enddo
                                                                                                                                                                                                                                                                               this must go into the field                                           